docs/index.rst

Removed reference to README from docs/index

Remove reference to README from docs

---

scripts/start.sh

Adding check that Connect worker is online before submitting Connector configs to REST API.

Adding check that Connect worker is online

---

docker-compose.yml

Plus a tweak to get C3 to work with KSQL

bump to 5.0.0-beta

---

docs/index.rst

This label enables linking from other topics.

Add label for KSQL Demo 3

---

docs/index.rst

Remove $ from commands

---

scripts/start.sh

Added a  variable to replace the relative script location references

Fixing the start.sh script

---

docker-compose.yml

Fixing CLASSPATH reference (due to CC-2422).
I did a quick smoketest and it looks good

DEVX-702: Validate and bump cp-demo to 5.1.1

---

docs/index.rst

DOCS-1573: Fix markdown-style link to C3 docs

---

scripts/connectors/submit_replicator_config.sh

We also want this to flow to `5.0.1-post`

DEVX-562: Disable provenance header explicitly (defaults to true <= 5.0)

---

docker-compose.yml

DEVX-952 Remove Connect Internal key/value converters

---

docker-compose.yml

This reverts commit 2d5e2dd84d956fd04c06dd21ad52d6314aad4da0.

Revert "DEVX-952 Remove Connect Internal key/value converters (#109)"

---

docker-compose.yml

DEVX-952 Remove Connect Internal key/value converters (#109)

---

README.md

Add link from cp-demo GH README to examples GH

DEVX-980: Add link from cp-demo GH README to examples GH

---

docker-compose.yml
scripts/ksql/run_ksql.sh
scripts/ksql/run_ksql_cmd.sh
scripts/ksql/run_ksql_commands.sh

This was my solution for running the ksql loading portion of the demo.  Added a few addl scripts which moved most of the processing into the docker container, which I hope makes things a little cleaner.
I targted DEVX-1032 first to isolate this change in a new PR, and then it will all be merged into 5.4.x after

DEVX-1032 refactor ksql script handling into mapped files

---

docker-compose.yml
scripts/ksql/run_ksql.sh
scripts/ksql/run_ksql_commands.sh
scripts/security/certs-create.sh
scripts/start.sh

After a test it appears these are the only changes required to address the various warnings in the key generation scripting.  All services appear to function normally after this change.   Note the minor change in the CA subject... the state attribute is different for the CA request vs the keytool genkey.

DEVX-1032 Addresses warnings in key scripting

---

scripts/app/map_topics_clients.py

These changes are required for python3 and are backward compatible with python2

ST-2811: Make map_topic_clients script python3 compatible.

---

scripts/start.sh

Client had issue with missing parenthesis https://confluent.zendesk.com/agent/tickets/25181
Feel free to accept PR or update yourselves then reject PR.  
Thank you.
Justin

Minor fix for missing parenthesis 

---

docker-compose.yml
docs/index.rst
scripts/connectors/submit_elastic_sink_config.sh
scripts/connectors/submit_replicator_config.sh
scripts/connectors/submit_wikipedia_irc_config.sh
scripts/control-center-modifications.sh
scripts/create-role-bindings.sh
scripts/ksql/run_ksql_commands.sh
scripts/security/ldap_users/01_base.ldif
scripts/security/ldap_users/02_KafkaDevelopers.ldif
scripts/security/ldap_users/10_alice.ldif
scripts/security/ldap_users/11_barnie.ldif
scripts/security/ldap_users/12_charlie.ldif
scripts/security/ldap_users/13_superuser.ldif
scripts/security/ldap_users/14_connect.ldif
scripts/security/ldap_users/15_schemaregistry.ldif
scripts/security/ldap_users/16_ksql.ldif
scripts/security/ldap_users/17_controlcenter.ldif
scripts/security/ldap_users/18_app.ldif
scripts/security/ldap_users/20_group_add.ldif
scripts/start.sh

Migrate LDAP user names and server

---

docker-compose.yml

Added/modified comments in docker-compose.yml to reflect the Slack conversation today.

DEVX-1703: Explain purpose of each set of RBAC-related configs

---

docs/index.rst

fix (docs): wikipedia typo

---

docker-compose.yml

explaining our usage of environment variables here.

DEVX-1719 adds documentation to docker-compose files

---

docker-compose.yml

DEVX-1812: remove confluent.authorizer.group.provider

---

docs/index.rst

DEVX-1957: add promo code to docs

---

docs/index.rst

This PR is a docs change only.
Validation:

DEVX-698: cp-demo: Add link to docker-compose file for config examples

---

.github/pull_request_template.md

DEVX-2155: Address checkbox behavior with comments

---

scripts/start.sh

Just a quick typo fix in startup logging.
None.

Fixed typo in startup logging

---

docker-compose.yml

Bump `tools` container `training-tools` image tag to 6.0.
Prior art #211 .
[ ] Documentation

DEVX-2202: Update the training-tools container image to 6.0

---

docs/index.rst

https://confluentinc.atlassian.net/browse/DOCS-5954
Identified in go-live for docs. 

[BLOCKER] DOCS-5954 - Fix broken link in tutorial

---

docs/index.rst
scripts/helper/functions.sh

https://confluentinc.atlassian.net/browse/DEVX-2282
cp-demo will not work if number of cores is 1.

DEVX-2282: Add to pre-flight check: number Docker cores

---

docs/index.rst

https://confluentinc.atlassian.net/browse/DEVX-2287
Broken link

DEVX-2287: Fix docs link to throttle_consumer.sh

---

scripts/start.sh

https://confluentinc.atlassian.net/browse/DEVX-2312
cp-demo changed how certs are generated: this forces CLEAN for users who are upgrading from earlier commits/versions

DEVX-2312: Change trigger for CLEAN=true

---

docs/index.rst

https://confluentinc.atlassian.net/browse/DEVX-2318
https://confluentinc.atlassian.net/browse/DOCS-6170

DEVX-2318 DOCS-6170: Show output in RP command

---

docs/index.rst

https://confluentinc.atlassian.net/browse/DEVX-2451
schema ids changed when ksqlDB queries changed

DEVX-2451: Update schema id from 11 to 9

---

scripts/connectors/submit_elastic_sink_config.sh
scripts/connectors/submit_replicator_config.sh
scripts/connectors/submit_wikipedia_sse_config.sh
scripts/helper/functions.sh
scripts/start.sh

https://confluentinc.atlassian.net/browse/DEVX-2453
Fail fast if connector submission fails

DEVX-2453: Add check to catch Connect error when submitting connector

---

docs/hybrid-cloud.rst
scripts/ccloud/create-ccloud-workflow.sh

Sister PR: confluentinc/examples#917

DEVX-2338: transition ccloud-generate-cp-configs from file to function

---

docs/hybrid-cloud.rst
scripts/ccloud/create-ccloud-workflow.sh
scripts/helper/functions.sh
scripts/start.sh
scripts/stop.sh

https://confluentinc.atlassian.net/browse/DEVX-2444

DEVX-2444: set EXAMPLE for ccloud-stack

---

docs/overview.rst

https://confluentinc.atlassian.net/browse/DOCS-7214
Fix typo.

DOCS-7214 - Minor type fix discovered by translators

---

docs/troubleshooting.rst

https://confluentinc.atlassian.net/browse/DEVX-2549
Address issue seen in community

DEVX-2549: Warn users not to do just docker-compose up

---

docker-compose.yml
tools/Dockerfile-tools

https://confluentinc.atlassian.net/browse/DEVX-2545
Confluent CLI v1.18.0 performance is better (separate investigation as to why)

DEVX-2545: cp-demo startup time increased: role binding time

---

docs/hybrid-cloud.rst

DEVX-2558: ccloud min ver to 1.25.0

---

docs/Makefile
docs/README.md
docs/autoreload.py
docs/conf.py
docs/requirements.txt
docs/settings.sh
docs/setup-venv.sh

Make local build possible in cp-demo. If this works, feel free to adapt to other DEVX doc repos. For instructions, see https://github.com/confluentinc/cp-demo/pull/324/files#diff-0b5ca119d2be595aa307d34512d9679e49186307ef94201e4b3dfa079aa89938

Add local build to cp-demo

---

docs/Makefile
docs/README.md
docs/autoreload.py
docs/conf.py
docs/requirements.txt
docs/settings.sh
docs/setup-venv.sh

Manual merge 61x to 62x

---

docs/on-prem.rst

On-prem tutorial docs tweaks and formatting fixes
Built and sanity checked docs locally

On-prem docs tweaks

---

docs/settings.sh

[ST-5182] Removing reference to docs-independent

---

docs/on-prem.rst

https://confluentinc.atlassian.net/browse/DOCS-8473
Update error code

DOCS-8473: update error code in step

---

docker-compose.yml
docs/hybrid-cloud.rst
docs/on-prem.rst
docs/teardown.rst
scripts/ccloud/create-ccloud-workflow.sh
scripts/ccloud/destroy-ccloud-workflow.sh
scripts/helper/create-role-bindings.sh
scripts/helper/functions.sh
scripts/validate/validate_bindings.sh
scripts/validate/validate_rest_proxy.sh
tools/Dockerfile-tools

Update `confluent` v1 / `ccloud` syntax to `confluent` v2 syntax.

CLI-1398: Update CLI references to v2

---

scripts/ccloud/create-ccloud-workflow.sh

Simplified code provided by https://github.com/confluentinc/examples/pull/1053

DEVX-2695: sister PR to simplify getting SA

---

docs/on-prem.rst

https://confluentinc.atlassian.net/browse/DEVX-2699

DEVX-2699: Clarify cp-demo Gitpod support model is best effort

---

docker-compose.yml

https://confluentinc.atlassian.net/browse/DEVX-2703
Address https://cwiki.apache.org/confluence/display/KAFKA/KIP-208%3A+Add+SSL+support+to+Kafka+Connect+REST+interface

DEVX-2703: update connect configurations for KIP-208

---

scripts/helper/create-role-bindings.sh

Ref:
1. https://confluentinc.atlassian.net/browse/DGS-3021
2. https://confluentinc.atlassian.net/browse/DEVX-2717

Use the correct default license topic

---

docker-compose.yml
docs/hybrid-cloud.rst
docs/on-prem.rst
scripts/ccloud/create-ccloud-workflow.sh
scripts/helper/create-role-bindings.sh
scripts/helper/functions.sh
scripts/start.sh
scripts/validate/validate_bindings.sh
scripts/validate/validate_rest_proxy.sh
tools/Dockerfile-tools

https://confluentinc.atlassian.net/browse/DEVX-2721

DEVX-2721: Prep cp-demo for 7.1.0

---

.gitpod.yml
docker-compose.yml
scripts/helper/functions.sh
scripts/start.sh

Update to use modern [compose specification](https://docs.docker.com/compose/compose-file) and incorporate health checks. This will lead hopefully to more predictable behavior and fewer transient errors since services will be guaranteed to be up when receiving requests.

Update docker compose file format

---

docker-compose.yml

https://confluentinc.atlassian.net/jira/software/c/projects/TMM/issues/TMM-29
This PR adds comments in docker-compose.yml about the configurations required for Confluent Health+
These are just comments, so they don't affect runtime behavior
Is it readable? Is it correct?

TMM-29: Add Health+ Configuration Placeholders in Comments

---

docs/hybrid-cloud.rst

https://confluentinc.atlassian.net/browse/TMM-81
make it clear where the schema link config file lives when it is first introduced

TMM-81: clarify the location of the schema link config file

---

scripts/helper/create-role-bindings.sh

This PR backports the fix made in - https://github.com/confluentinc/cp-demo/pull/412
While testing cp-demo with new patches, we hit same issues as mentioned in the above PR. The same code change fixed the issue.
Tested with pre-ga images upcoming new patch - 6.2.7 and 7.0.6

Point license resource to correct topic

---

docs/hybrid-cloud.rst
docs/includes/metrics-api-intro.rst
docs/index.rst
docs/on-prem.rst
docs/overview.rst
docs/teardown.rst
docs/troubleshooting.rst

This PR improves the titles for the cp-demo tutorial to be more accurate. 
**Current**
**Updated**

Fix cp-demo titles

---

docs/hybrid-cloud.rst

https://confluentinc.atlassian.net/browse/DOCS-18677

DOCS-18677 - Fix links

---

docs/overview.rst

Adds Cloud CTA to cp-demo page. 
Increase awareness of fully-managed Cloud solution for Apache Kafka. 

DOCS-23929 - Add Cloud CTA to top Platform pages

---

docs/overview.rst

Reverts confluentinc/cp-demo#443

Revert "DOCS-23929 - Add Cloud CTA to top Platform pages"

---

.github/CODEOWNERS

Update CODEOWNERS, add devx, product and SEs

Update CODEOWNERS, add devx, product and SEs

---

.github/CODEOWNERS

Resolved conflict, updated CODEOWNERS.  Fixes CODEOWNERS to correct on-line format.

Resolve conflict, update CODEOWNERS

---

.github/ISSUE_TEMPLATE/bug_report.md
docker-compose.yml
scripts/app/throttle_consumer.sh
scripts/ccloud/cluster-link-scratch.sh
scripts/ccloud/create-ccloud-workflow.sh
scripts/ccloud/destroy-ccloud-workflow.sh
scripts/connectors/stop_elasticsearch_sink.sh
scripts/connectors/submit_elastic_sink_config.sh
scripts/connectors/submit_wikipedia_sse_config.sh
scripts/helper/functions.sh
scripts/helper/refresh_mds_login.sh
scripts/ksqlDB/run_ksqlDB.sh
scripts/sbc/add-broker.sh
scripts/sbc/docker-compose.yml
scripts/sbc/validate_sbc_add_broker_completed.sh
scripts/sbc/validate_sbc_add_broker_plan_computation.sh
scripts/sbc/validate_sbc_add_broker_reassignment.sh
scripts/sbc/validate_sbc_kill_broker_completed.sh
scripts/sbc/validate_sbc_kill_broker_started.sh
scripts/start.sh
scripts/stop.sh
scripts/validate/validate_bindings.sh
scripts/validate/validate_ksqldb_processing_log.sh
scripts/validate/validate_rest_proxy.sh

This PR merges branch 7.9.2-post into 8.0.0-post, resolving 1 conflict.  It is a replacement for https://github.com/confluentinc/cp-demo/pull/487 .
This brings in the `docker-compose`-> `docker compose` change from https://github.com/confluentinc/cp-demo/pull/478 .

8.0.0 post merge conflicts 7.9.2 post
