confluentinc/cp-demo

README.md
Https protocol is so much easier to use: it is accessible behind firewalls and proxies.
It also helps github beginners that either have no account or did not yet do any ssh key setup.
Also this what is already used in https://github.com/confluentinc/cp-demo/blob/master/.gitmodules
=> Use https git protocol

README.md
Clarify from where `make clean all` needs to be run. It's there if you go the submodule route, but not explicit if you don't
=> Add clarification to point 3

Makefile
Fix for:
~/Code/cp-demo$ make
if [[ ! -d "connect-plugins" ]]; then mkdir "connect-plugins"; fi
/bin/sh: 1: [[: not found
make install
make[1]: Entering directory '/home/mitchellh/Code/cp-demo'
if [[ ! -d "connect-plugins" ]]; then mkdir "connect-plugins"; fi
/bin/sh: 1: [[: not found
make[1]: Leaving directory '/home/mitchellh/Code/cp-demo'
mvn clean package -f kafka-connect-irc/pom.xml
[INFO] Scanning for projects...
=>  fix for ubuntu sid sometimes linking /bin/sh to /bin/dash

README.md
Bullet sections should be indented to make sure numbering remains consecutive & that the content is indented correctly when rendered. Github seemed ok with it as is but the Markdown rendered elsewhere (e.g. Marked2) was not so pretty :)
=> Fix markdown bullet indents & minor nits

scripts/stop.sh
if 'docker ls' returns no volumes (cause you already stopped and cleaned everything) you cannot start cp-demo again, because start.sh is using stop.sh which is going to fail on xargs command with no (null) param.
=> improve stop.sh for deleting volumes

docker-compose.yml, docs/index.rst, scripts/app/start_consumer_app.sh, scripts/app/stop_consumer_app_group_graceful.sh, scripts/app/stop_consumer_app_group_ungraceful.sh, scripts/consumers/listen.sh, scripts/consumers/listen_EN_WIKIPEDIA_GT_1_COUNTS.sh, scripts/consumers/listen_WIKIPEDIANOBOT.sh, scripts/consumers/listen_wikipedia.failed.sh, scripts/consumers/listen_wikipedia.parsed.sh, scripts/ksql/run_ksql.sh
This PR will fix two things:
Executing the run script in the KSQL server (was a problem for linux, not mac os)
Namespacing and how containers are called; no longer auto-generated but rather pre-defined in the docker-compose file using `container_name`. This change was required for compatibility with docker-compose v 1.21.0 released 13 days ago
=> #45: fix run script for linux

docker-compose.yml, docs/index.rst, scripts/connectors/submit_replicator_config.sh
1. DEVX-658: disable offset.timestamps.commit in Replicator so that wikipedia.parsed.replica does not show up in Control Center consumer lag (relevant when Replicator consumer lag shows in C3 in 5.1.1)
2. DEVX-657: do not overload `connect-replicator`, add comment to Docker compose
=> DEVX-658, DEVX-657:

scripts/start.sh
Comparison of times for ```./scripts/start.sh``` to complete:
5.1.2-post: avg 4:03 (3:52, 4:16, 4:03)
PR w/ 3s gap wait: 2:59 (3:03, 3:02, 2:53)
Savings of 60+ seconds
Note:
Original PR w/ 10s gap wait: avg 3:17 (3:06, 3:24, 3:23)
=> DEVX-787: optimize start time

scripts/start.sh
If `keytool` isn't installed, `docker-compose up` still runs, but the certificates never got created, so Kafka fails to start.
=> Add "keytool" to the list of applications that get verified

scripts/dashboard/set_elasticsearch_mapping_bot.sh, scripts/dashboard/set_elasticsearch_mapping_count.sh
Having the EOF formatted as
```EOF);```
instead of
```
EOF
)
```
causes the following warning:
``warning: here-document at line 50 delimited by end-of-file (wanted `EOF').``
By removing the semi-colon and adding a LF between the EOF and the ), the warning goes away.
=> remove eof warnings

docker-compose.yml
Fix: remove `$PWD` from the `docker-compose.yml` file.  
Result: `start.sh` can be run either from the main directory or the `scripts/` subdirectory
=> DEVX-1033: CP-Demo will silently fail if launched from scripts directory

docker-compose.yml
Moves env `discovery.type: "single-node"` from `kibana` service where it is unneeded, to `elasticsearch` service.
To test current problem, on a standard AWS EC2 machine with Docker and Compose, try and bring-up the `elasticsearch` service with `docker-compose up -d --no-deps elasticsearch`.  Provided Docker Compose creates a network that Elastic determines is non-local and could be a production deployment (_bound or publishing to a non-loopback or non-link-local address, enforcing bootstrap checks_) it will run its bootstrap checks, which could fail e.g.:
```
elasticsearch                  | [2019-08-18T10:37:05,699][INFO ][o.e.d.DiscoveryModule    ] [pRtsMlB] using discovery type [zen]
elasticsearch                  | [2019-08-18T10:37:10,203][INFO ][o.e.n.Node               ] …
```
=>  Add env discovery.type: "single-node" to elasticsearch service

scripts/stop.sh
Uses docker-compose to remove our volumes instead of ones outside our compose project.  
Verified cleanup with the following before, during and after running cp-demo:
```
[I] ➜ docker volume ls
DRIVER              VOLUME NAME
cp-demo/scripts on  DEVX-1166 [!]
[I] ➜ docker volume ls
DRIVER              VOLUME NAME
local               1ec4827957cfa0e71a3ab99912c193a78c30f2497b84b26cafa53a75b0336747
local               3daf7c9a15cdf925398bc1c62e3e2091d266c5012e11ac2fcc6c7450795781a3
local               4e7701e17b89d27fc77fb17d55253508e70bbc309284de774a067da962a9801a
local               8a0b6334748589a7c4199de34163b5ba158cf53b0d53343c5da4021ac7e3a4be
local               8d450c9ddddef417ec33b8194557f46cb9d00aeb0418d8d29d706e4e1c98717a
local …
```
=> DEVX-1166 only removes our docker volumes, and simplifies ksql-server-start shutdown call

docker-compose.yml
modified zookeeper version so it is the same as CP version instead of latest (i don't know if we guarantee that versions are compatible with newer Zookeepers in case that happens), but am okay if we decide we don't want that
modified parameter to deal with _confluent-licenses topic and only having 2 brokers in this demo.
Will update kafka-connect to server-connect in another PR (currently a blocking bug)
=> change zookeeper version to tie to CP and add license replication config

docker-compose.yml
cp-demo: Bump 5.4.x branch
Issue:
Docker image tag got bumped to in-correct value for docker image tags.
- learn about all the changes required for devx repositories both during branch cut & release version bumps.
- address immediate issue by bumping these to 5.4.x-latest
- update branch cut steps to avoid future issues:
https://confluentinc.atlassian.net/wiki/spaces/TOOLS/pages/582517464/Major+Minor+Release+Release+Branch+Creation+Feature+Freeze#Major/MinorRelease:ReleaseBranchCreation(FeatureFreeze)-DevXFollowups
Automate via tooling - Added jira to fix tooling:
https://confluentinc.atlassian.net/browse/ST-2650
=> cp-demo: Bump 5.4.x branch

scripts/start.sh
On RHEL images the nc command output is formatted differently and does not contain the word we currently search for in order to determine success. I did test that this command will return a non-zero error code if it fails, so there is no need to parse the output. This will continue to work on Debian and RHEL images.
=> ST-2811: Making the connection check to wikimedia irc work on rhel

docker-compose.yml
The curl commands were failing with the rhel images because the key was not strong enough. This is the error:
curl: (35) error:141A318A:SSL routines:tls_process_ske_dhe:dh key too small
This change will resolve that issue so that cp-demo can work with our new rhel ubi images when making curl commands. 
I tested this by running cp-demo using rhel and debian images.
=> ST-2811: Fix curl connection issue with rhel images

scripts/app/map_topics_clients.py
When running this script using Python3 the subprocess command will return the data in bytes, where as in python2 it returned a unicode string. This causes the call to split each line fail. This change will make it so the call returns unicode. I tested this using Python3.6 and Python2.7
=> ST-2811: Make map topics clients script work with python3

docker-compose.yml
As per: https://confluent.slack.com/archives/C09EP1SS3/p1579053207364100
These changes are required.
=> Fix 5.4.0 post-release docker image tags

docker-compose.yml
Before we can get the tool team's tooling to automate these updates, we need to adhere to the set up standard, which is to use the `major.minor.x-latest` convention we're doing in the `major.minor.x` branches - I noticed that master is not following this convention right now, and also had a bad version in zookeeper.
=> Master should be 5.5.x-latest not 5.5.0-SNAPSHOT

scripts/start.sh
Some users reported 120 seconds is not enough wait time for connect to come up
=> DEVX-1726: improve connect bring (part 1 of 3)

docker-compose.yml
Before:
```
connect             67576369569e        6.15%               1.908GiB / 7.778GiB
```
After:
```
connect             962e93b24c9f        14.60%              711.2MiB / 7.778GiB
```
=> DEVX-1729: Reduce Connect's memory utilization through GC reconfiguration

docker-compose.yml
Note: this rev looks like it could be easily-missed since versions are externalised to `config.env` e.g. `CONFLUENT_DOCKER_TAG=5.5.0`.  I wondered if another variable could be added close-by, or even co-opt `CONFLUENT_SHORT=5.5` so that they would be updated together - thoughts?
=> Updated the training-tools container image to 5.5

.gitignore, docker-compose.yml, scripts/start.sh
Fixes two problems:
MDS timeout (kafka broker never starts due to missing pem file) and this error:
```
Building custom Docker image with Connect version 5.5.0 and connector version 5.5.0
docker build --build-arg CP_VERSION=5.5.0 --build-arg CONNECTOR_VERSION=5.5.0 -t localbuild/connect:5.5.0-5.5.0 -f Dockerfile-confluenthub .
unable to prepare context: unable to evaluate symlinks in Dockerfile path: lstat /Users/yeva/git/cp-demo/scripts/Dockerfile-confluenthub: no such file or directory
ERROR: Docker image build failed. Please troubleshoot and try again.
```
=> DEVX-1794: Enable cp-demo start script to be run from scripts subfolder

docs/index.rst
At the end of `consumers` section, there is a reference to `Brokers -> Production` that seems misplaced.
Changes:
- "Brokers -> Production" to "Brokers -> Consumption"
- Update link from deprecated view to a more updated one.
- Align format.
=> [MINOR] fix (docs): misplaced paragraph

docker-compose.yml
Current KStreams version was using versions cp-5.4.0/kafka-2.4.0. New image is available :)
New image: <https://hub.docker.com/layers/cnfldemos/cp-demo-kstreams/0.0.6>
Ref: https://github.com/confluentinc/demos-common/pull/3
=> Bump KStreams Demo version

docker-compose.yml
With our UBI images , the jars needed for "Cub" are in /usr/share/java/cp-base-new/* , but current cp-demo points to /etc/confluent/docker/docker-utils.jar
Since 6.0.x is using UBI images by default, we need to switch this for cp-demo to work.
Validated by manually editing docker-compose with these changes and making sure ZK and Kafka ready were working correctly.
=> [DEVX-1885] update cub classpath for UBI-based images

docker-compose.yml, scripts/security/ldap_users/20_group_add.ldif, scripts/security/ldap_users/21_restAdmin.ldif, scripts/validate/validate_bindings.sh
This switches rest proxy to use it's own LDAP user and adds the user to LDAP.  In the future, may need to have specific role bindings for rest proxy, so this enables that and is a better separation vs. using connect admin.
Testing: With this change, brought up cp-demo and walked through security section in documentation with all rest proxy commands.
Includes on other minor change to add a wildcard for monitor-interceptors in connect classpath (since there is only one jar, this just makes it easier in case version matching is not exact)
=> [DEVX-1889] Update restproxy creds

docker-compose.yml, scripts/helper/create-role-bindings.sh
In order for SR and Rest Proxy to use the confluent license manager for trial license management, they need read/write access on the _confluent_license topic. This adds those role bindings.
Testing: Confirmed before this change that rest / SR failed to start due to lack of topic access and with this change both SR and Rest start fine (get past licensing) - Demo Not fully tested e-2-e
One additional change added here to modify ksql authorization to support a recent switch to vert.x auth
Testing: Internal error before this change due jetty no longer being available. Authorization was successful after this change.
=> [DEVX-1887] updated cp-demo to use license manager instead of ZK for trial license - SR & Rest

scripts/helper/functions.sh, scripts/start.sh, scripts/validate/validate_connectors_running.sh
At the moment if `cp-demo` fails it tells the user `Please troubleshoot and run again.`, but it doesn't tell them *how* to troubleshoot. Users _may_ be following [the docs](https://docs.confluent.io/current/tutorials/cp-demo/docs/index.html) already and see the [troubleshooting](https://docs.confluent.io/current/tutorials/cp-demo/docs/index.html#troubleshooting) section - but they may not :) In this case users may simply abandon the demo, or turn to the community for help: 
We can smooth the user's journey by providing the link to the troubleshooting doc directly. They may still need help (and we should consider expanding this feedback message perhaps to direct them to http://cnfl.io/slack if they are still stuck?), but this at least gets them on the right tracks. 
If the URL of the …
=> Add troubleshooting URL to cp-demo

docs/index.rst, scripts/helper/functions.sh
I suspect that since:
```
commit be92587f6fbe2884df8b6e9374d0f12a38675245
Author: Yeva Byzek <ybyzek@users.noreply.github.com>
Date:   Tue Apr 14 22:44:16 2020 -0400
DEVX-1707: Remove scripts/app/map_topics_clients.py from cp-demo (#196)
```
... `cp-demo` does not currently have any _launch-time_ dependencies on a Python runtime, so the check could be removed.  There is a reference in the docs Makefile, but that's a separate concern.
This came up when I attempted to launch on one of the Linux flavours which packages Python 3 such that binaries are `python3` and there is no `python` (and deprecated Python 2 is not installed).  I could create a symlink, but it looks like this check is now redundant anyway since the above removal of a Python script.
=> Removed python check and doc-mention

docker-compose.yml
Once https://github.com/confluentinc/ksql-images/pull/55 is merged, security plugins will be installed in a separate directory, so we will need to modify cub classpath to include the security plugins.  Verified with private ksqldb images built from that PR.
=> modify ksqlDB CUB_CLASSPATH given relocation of security plugins

env_files/config.env, scripts/start.sh
CONNECTOR_VERSION was incorrect for the 6.0.x branch
@rspurgeon this implements the solution we discussed today
@sdanduConf note that this enforces the proper workflow for testing cp-demo pre-GA, which requires user environment to have a local build of Replicator
=> DEVX-2016: Bump CONNECTOR_VERSION

docker-compose.yml
Verified running streams-demo and wikipedia-monitor consumer group
=> DEVX-2082: Upgrade cp-demo-kstreams to latest based on 6.0 (0.0.7 image version)

docker-compose.yml
ksqlDB does not need {{oauth.jwt.public.key.path}} and {{confluent.metadata.public.key.path}}
Validated changes
=> DEVX-1947: Remove unnecessary configuration commands from RBAC/ksqlDB

docker-compose.yml
Companion PR from changes in https://github.com/confluentinc/demos-common/pull/5
Changed docker image pushed to docker hub here: https://hub.docker.com/layers/cnfldemos/cp-demo-kstreams/0.0.8/images/sha256-5b4ff1a875a9716aa2b8f144606d18a609447b9f6d88a19b429896eaa581e805?context=repo
=> DEVX-1778; bump cp-demo-kstreams container v

.gitignore, scripts/helper/functions.sh, scripts/security/certs-create.sh
Use xargs in parallel mode to create certificates in-parallel in the background.  Certificate generation currently occurs as a large serial batch near the start of the `cp-demo` launch script, and can take some time.  Here's some comparison timings:
Before:
```
$ time ./certs-create.sh
Generating a 2048 bit RSA private key
...................................................+++
......+++
writing new private key to 'snakeoil-ca-1.key'
-----
------------------------------- kafka1 -------------------------------
Signature ok
subject=/C=US/ST=Ca/L=PaloAlto/O=CONFLUENT/OU=TEST/CN=kafka1
Getting CA Private Key
Certificate was added to keystore
Certificate reply was installed in keystore
Certificate was added to keystore
Certificate stored in file <kafka1.der>
Importing keystore …
```
=> Make certificate generation parallel and faster

docker-compose.yml, scripts/ksqlDB/run_ksqlDB.sh, scripts/ksqlDB/run_ksqlDB_commands.sh
https://confluentinc.atlassian.net/browse/DEVX-1368
Run ksqlDB commands as RUN SCRIPT
With PR:
```
real    1m23.779s
user    0m0.534s
sys     0m0.097s
```
Without PR:
```
real    3m19.011s
user    0m0.639s
sys     0m0.132s
```
=> DEVX-1368: cp-demo: revert running ksqlDB commands back to RUN SCRIPT

scripts/helper/functions.sh
The `awk` util is used in some helper scripts, and whilst commonly-installed on many platforms, it is optional.  We should verify it is installed.
e.g. https://github.com/confluentinc/cp-demo/blob/999e3b2002243cb066ef234f959c1b2de2f313e8/scripts/helper/functions.sh#L44
=> Added awk tool to pre-flight verify_installed checks

scripts/security/certs-create-per-user.sh
openssl x509 ... option -CAcreateserial isn't parallel-friendly,  and cert-generation
was recently parallelized.  This created an overwrite/corruption condition on the
file used by -CAcreateserial, in our case:
>  unable to load number from ./snakeoil-ca-1.srl
Whilst a serial can be loaded from a specific file via -CAserial [file], it's
not clear how to interact this with -CAcreateserial option for a unique filename,
if that's even possible.
The serial has to be unique and <= 20 octets.  openssl seems to be generating
monotonic-increasing (time-based?) ones, but 8 octests random is plenty for our
demo certs.
Replaced with an awk script generating 8 octets, pass to -set_serial for each
cert.
https://confluentinc.atlassian.net/browse/DEVX-2203 …
=> DEVX-2203: replace -CAcreateserial with parallel-safe random

scripts/security/certs-create-per-user.sh
`cp-demo` is secured (by RBAC) and Control Center can currently be accessed via http://localhost:9021, or over TLS via https://localhost:9022.  Obviously HTTPS is better to demonstrate security, but as a stand-up demo, all cp-demo's CAs are self-signed, so the certificates they sign aren't automatically trusted by browsers, and fair-enough!
It can however be useful when using the demo to carefully ignore and bypass these trust-warnings, accessing Control Center over HTTPS.  However, browsers are becoming stricter, and the path familiar especially to developers e.g
Chrome: Your connection is not private (error page)
-> Click Advanced
-> Read warning
-> Click link: Proceed to localhost (unsafe)
... is not even always offered anymore.  Browsers …
=> DEVX-2209: Improve self-signed certificates for better browser tolerance

docker-compose.yml
This PR creates Control Center config property `confluent.controlcenter.streams.cprest.url` which is required for the Self Balancing Clusters UI.
This resolves a 403 unauthorized error from the C3 UI when accessing `/api/kafka-rest`.  With this property set, the Self Balancing Cluster feature is now enabled in the UI.
Note that this change doesn't perform any set-up for demo of the Self Balancing Cluster feature.
[ ] Documentation
[x] Run cp-demo
=> DEVX-2231: add CONTROL_CENTER_STREAMS_CPREST_URL for Self Balancing Clusters

Dockerfile-confluenthub, Dockerfile-local, scripts/start.sh
https://confluentinc.atlassian.net/browse/DEVX-2233
- Without this fix, when certs copy precede Confluent Hub pulls, all connectors need to be redownloaded --> and connect image build takes 0m42.256s .
- With this fix, when Confluent Hub pulls precede certs copy, connectors do NOT need to be redownloaded --> add connect image build takes 0m10.422s .
Savings of about 30s
```
Step 5/12 : RUN confluent-hub install --no-prompt cjmatta/kafka-connect-sse:latest
---> Using cache
---> 74ac43129c60
Step 6/12 : RUN confluent-hub install --no-prompt jcustenborder/kafka-connect-json-schema:latest
---> Using cache
---> 1250919c105d
Step 7/12 : RUN confluent-hub install --no-prompt confluentinc/kafka-connect-replicator:${CONNECTOR_VERSION}
---> Using cache …
```
=> DEVX-2233: Reorder Dockerfile to reuse a cached layer

.dockerignore
Connect has a local `docker build` these days - we should have a basic `.dockerignore` to reduce the size of the build-context and avoid any accidents.
None.
=> Added a basic .dockerignore

docs/index.rst, scripts/validate/validate_rest_proxy.sh
https://confluentinc.atlassian.net/browse/DEVX-2247
The following lines can be removed from curl commands to SR because `ssl.client.auth` is disabled:
```
--cert /etc/kafka/secrets/schemaregistry.certificate.pem \
--key /etc/kafka/secrets/schemaregistry.key \
```
=> DEVX-2247: Remove cert and key from SR command

docker-compose.yml
There were duplicate environment variables in the docker-compose file.
Removed env vars and ensured that everything starts correctly.
Whatever you feel is necessary.
=> remove redundant env vars

scripts/ksqlDB/statements.sql
For whatever reason, one of the ksqlDB queries bundled with this demo did not use the proper syntax for accessing a struct property. The result was that part of the demo was broken. The query that creates the `en_wikipedia_gt_1` table never resulted in any data with the old syntax.
According to the [official documentation](https://docs.ksqldb.io/en/latest/how-to-guides/query-structured-data/) the proper syntax is `field->sub_field` not `'field.sub_field'`. I'm not sure why this other syntax is here in the example? Maybe the ksqlDB syntax changed and this example was not updated? I'm new to ksqlDB, and came across this as part of the process of evaluating it as a potential technology to incorporate into our operations.
With the correction, the `en_wikipedia_gt_1` table and corresponding …
=> Fix struct access syntax in ksqlDB query

docker-compose.yml
https://confluentinc.atlassian.net/browse/DEVX-2279
This PR removes the CPU limits on all containers, dramatically improving startup time, and generally improving performance. The results of the following two test runs demonstrate the improvement (note: all containers were pulled prior to testing).
**CPU limited:**
```text
real	14m40.234s
user	5m35.371s
sys	0m22.642s
```
**CPU unlimited:**
```text
real	6m3.344s
user	5m25.884s
sys	0m23.217s
```
It can be seen that the actual CPU time was essentially the same. However the limits placed on CPU allocation in the first test resulted in the total real time being dramatically longer.
macOS Catalina 10.15.7 (2.4 GHz 8-core i9, 64GB RAM)
Docker 19.03.13 (limited to 12 CPUs threads and 48GB RAM)
```text
Client:
Debug Mode: false
Plugins:
scan: …
```
=> DEVX-2279: remove container cpu limits

docker-compose.yml
The SSL Cipher Suite specified in the docker-compose.yml file is not supported by Google Chrome, as it is apparently considered to be insecure. This PR changes the cipher suite to a similar one that is supported by Google Chrome to allow for connecting to e.g. the Schema Registry server from the browser for manual data exploration via the REST API.
I have run the demo on Docker on Linux using the `scripts/start.sh` script and it continues to work fine after this change, with the notable difference that my Chrome browser will now allow me to make TLS connections to e.g. the schema registry on port 8085.
Accept this if it seems reasonable to you. It's a pretty low-risk, low-impact configuration change.
=> Switch to a cipher suite that Chrome supports.

Dockerfile-local
When building in local/SNAPSHOT mode on `6.0.x` branch, I got a permissions error, since the container now runs as `appuser` during build, but `COPY` is `root` by-default:
```
=> [4/8] COPY confluentinc-kafka-connect-replicator-6.0.1-SNAPSHOT.zip /tmp/confluentinc-kafka-connect-replicator-6.0.1-SNAPSHOT.zip                                                                                                    0.1s
=> ERROR [5/8] RUN confluent-hub install --no-prompt /tmp/confluentinc-kafka-connect-replicator-6.0.1-SNAPSHOT.zip                                                                                                                      1.0s
------
> [5/8] RUN confluent-hub install --no-prompt /tmp/confluentinc-kafka-connect-replicator-6.0.1-SNAPSHOT.zip:
#9 0.648 Running in a …
```
=> Added chown appuser for Replicator zip COPY when building in local/SNAPSHOT mode

docs/index.rst
1.16.0 is the minimum version for compose file version 2.3.  [RBAC](https://github.com/confluentinc/cp-demo/pull/164/files#diff-8d068e8797e88947c320f79e856c3e16a72b730124a8f9d7031e2c4680dfa534R57) bumped the Docker Compose file version to 2.3, which requires min 1.16.0.
cp-demo 6.0.0-post branch will launch with Docker Compose 1.16.0.
=> Doc: updated min Docker Compose version to 1.16.0 (was 1.14.0)

scripts/env.sh, scripts/helper/functions.sh, scripts/stop.sh
https://confluentinc.atlassian.net/browse/DEVX-2311
Change pattern match to detect pre-GA
Note: cp-demo still doesn't run on 6.1.x due to `io.confluent.connect.replicator.monitoring.ReplicatorMonitoringExtension` error
=> DEVX-2311: cp-demo cannot detect pre-GA code with "-SNAPSHOT"

scripts/helper/create-topics.sh, scripts/helper/functions.sh, scripts/helper/topic.jq, scripts/start.sh
I was using the v3 REST API with `cp-demo` and figured changing topic-creation to use the v3 REST API would be a good addition.  This PR retires shelling-in to a container to run CLI tool `kafka-topics`, replacing with `POST` calls to https://localhost:8091/kafka/v3/clusters/${KAFKA_CLUSTER_ID}/topics .
This appears to be much faster, and would eliminate the need for efforts to parallelise topic-creation per #285 .
`curl` was missing from pre-flight installed checks, so added that too.
Some questions for reviewer:
- Currently we don't bother to use the same user …
=> DEVX-2277: Change topic creation to use Confluent Server v3 REST API

Dockerfile, scripts/helper/functions.sh
https://confluentinc.atlassian.net/browse/DEVX-2406
- Consistency is Docker org based on `REPOSITORY` var
- Remove unnecessary var
=> DEVX-2406: REPOSITORY not consistently used in all places in cp-demo

kstreams-app/build.gradle
https://confluentinc.atlassian.net/browse/DEVX-2204
Address:
```
> Task :jibDockerBuild
'jib.container.useCurrentTimestamp' is deprecated; use 'jib.container.creationTime' with the value 'USE_CURRENT_TIMESTAMP' instead
Setting image creation time to current time; your image may not be reproducible.
```
=> DEVX-2204: cp-demo: Update kstreams app jib timestamp usage

Dockerfile
https://confluentinc.atlassian.net/browse/DEVX-2235
To avoid a pint merge and given the changes to the Dockerfiles between `6.0.1-post` and `6.1.x`, I am suggesting to merge this branch into `6.1.x`. 
Given that we have been using the latest connector versions, I propose we pin to what those latest versions are. I validated my change by running cp-demo with the pinned versions.
=> DEVX-2235: Use explicit connector version numbers in Dockerfile

scripts/connectors/submit_replicator_to_ccloud_config.sh
https://confluentinc.atlassian.net/browse/DEVX-2432
Address the following warn message (by setting `topic.config.sync`; alternative was ACL management with `ALTER_CONFIGS`)
```
connect           | [2021-01-14 20:08:37,855] WARN Failed topic configuration check for destination topic wikipedia.parsed.ccloud.replica on task replicate-topic-to-ccloud-0 exception java.util.concurrent.ExecutionException: org.apache.kafka.common.errors.TopicAuthorizationException: Topic authorization failed.. Will retry later. (io.confluent.connect.replicator.ReplicatorSourceTask)
```
=> DEVX-2432: add topic.config.sync

docs/hybrid-cloud.rst, docs/includes/metrics-api-intro.rst, scripts/ccloud/create-ccloud-workflow.sh, scripts/ccloud/metrics_query_ccloud.json, scripts/ccloud/metrics_query_onprem.json
https://confluentinc.atlassian.net/browse/DEVX-2504
v2 is latest
=> DEVX-2504: use v2 instead of v1 for Metrics API

scripts/ksqlDB/statements.sql
https://confluentinc.atlassian.net/browse/KSE-286
In 6.2.0+, when multiple grouping criteria are used, ksqlDB requires the key format to be one of JSON, AVRO, PROTOBUF, DELIMITED, or JSON_SR. The default KAFKA format does not support multiple grouping criteria as of this version (and ksqlDB standalone 0.15+).
=> KSE-286: Fix multi-group-by persistence format

scripts/helper/functions.sh
Resolves https://github.com/confluentinc/cp-demo/issues/371
Delegates error messaging to the behavior of `docker -ps` CLI which results in 
`kevinblaisdell@manta scripts % ./start.sh Cannot connect to the Docker daemon at unix:///var/run/docker.sock. Is the docker daemon running?`
Can be removed in the future if docker CLI commands gracefully handle this consistently as `docker -ps` does.
=> add is docker daemon running to preflight checks

docker-compose.yml, kstreams-app/build.gradle, kstreams-app/src/main/java/io/confluent/demos/common/wiki/WikipediaActivityMonitor.java, kstreams-app/src/main/jib/app/start.sh
* Updates kstreams-app startup script to remove logging of unecessary information
* Publishes new kstreams-app (0.10) and updates version used in cp-demo (https://hub.docker.com/layers/cnfldemos/cp-demo-kstreams)
* Moves streams library dependencies to current cpVersion + "ce". Reason for "ce" requirement isn't totally known, but the monitoring-interceptors library appears to transitively bring in the "ce" version of kafka-clients, and if the "ccs" or AK versions of the streams library is used, runtime errors are encountered.
=> DEVX-2622 & DEVX-2640: Update kstreams deps to CP versions and redact logging

scripts/helper/functions.sh
use the $REPOSITORY variable isntead of the hardcoded confluentinc/ for container access in functions.  This is so credential generation will work for containers not in the public confluent repository
=> Use $REPOSITORY variable in functions.sh

scripts/sbc/docker-compose.yml
https://confluentinc.atlassian.net/browse/DEVX-2671
This PR ties up one loose end from https://github.com/confluentinc/cp-demo/pull/379 , which is to make mods to the `docker-compose.yml` file used by SBC.
First I validated that the SBC script breaks in 6.2.0-post, then validated that the PR fixes the issue
```
[17:17:06] ~/git/cp-demo(DEVX-2671) ✗: ./scripts/sbc/add-broker.sh 
Signature ok
subject=C = US, ST = Ca, L = PaloAlto, O = CONFLUENT, OU = TEST, CN = kafka3
Getting CA Private Key
Certificate was added to keystore
Certificate reply was installed in keystore
Certificate was added to keystore
Certificate stored in file <kafka3.der>
Importing keystore kafka.kafka3.keystore.jks to kafka3.keystore.p12...
Entry for alias kafka3 successfully …
```
=> DEVX-2671: complete PR #379

scripts/env.sh
https://confluentinc.atlassian.net/browse/DEVX-2686
Fix this error when running `add-broker.sh` from SBC demo:
```
cp-demo/scripts/sbc/../env.sh: line 30: GITPOD_WORKSPACE_URL: unbound variable
```
=> DEVX-2686: make null-safe reference to GITPOD_WORKSPACE_URL

scripts/helper/functions.sh
https://confluentinc.atlassian.net/browse/DEVX-2689
This PR fixes a regression (also described in DEVX-2689):
- DevX2676 introduces a `sudo` command (2x) to enable overwriting root-privileged files (in `functions.sh | create_certificates()`).
- This assumes passwordless sudo is enabled on the docker host system
- A fix was introduced approved and merged into 6.2.0-post in PR #396
- This fix was overwritten 4 days later in commit dd3b2f65fafc845a0abb0a8cc4defd884a1c6af7
* BEFORE code change: starting `cp-demo` with `CLEAN=true` was failing for me.
* AFTER re-applying the changes from the previous commit/PR
* I was able to run and re-run `cp-demo` with `CLEAN=true` …
=> fix regression devx-2689

docs/hybrid-cloud.rst, docs/on-prem.rst, env_files/config.env, scripts/helper/functions.sh, scripts/start.sh, scripts/validate/validate_rest_proxy.sh
https://confluentinc.atlassian.net/browse/DEVX-2720
DEVX-2720: fixes for failed runs on modern docker and docker-compose
I have not been able to isolate why these changes are required on my development machine. However, without these the cp-demo start script failed for a variety of reasons.  The return values from executions of docker-compose exec ... resulted in empty variables which evaluated to various runtime error in the start script. 
This set of changes does not directly address the issues identified in DEVX-2720 but instead was required by me to get the demo to run at all.  I will next attempt to understand and address the issues noted in the Jira issue.'
=> TMM-3: Add `--no-TTY` to `docker-compose exec` commands to fix validation scripts in newer versions on docker

docs/hybrid-cloud.rst, docs/on-prem.rst, scripts/helper/functions.sh, scripts/start.sh, scripts/validate/validate_rest_proxy.sh
https://confluentinc.atlassian.net/browse/TMM-76
There is a breaking change in the TTY output behavior of `docker-compose exec` between docker compose v1 and v2:
- https://github.com/docker/compose/issues/9202
Since we explicitly set `container_name` in `docker-compose.yml`, `docker exec` works the same as `docker-compose exec`, except by not using `docker-compose`, we avoid the discrepancy between dc v1 and v2.
=> Replace docker-compose exec with docker exec

.gitpod.yml, scripts/env.sh, scripts/helper/functions.sh, scripts/start.sh, scripts/stop.sh
Right now, the `init` step in gitpod starts and stops cp demo. If a prebuild isn't available, that means users will experience start, stop, and start again.
Other improvements that may be in scope:
- limit the number of prebuilds that run to only the default branch and PRs.
- add prebuilds as a status check to PRs to act as some light CI / automated validation 
- fix transient issue where zookeeper gets confused after restart and brokers barf
- fix issue where connect isn't ready in time (more of a hack, but a proper fix is out of scope)
=> modify gitpod init for better behavior when prebuilds are not available

.gitpod.yml
As of right now, CP Demo is too CPU intensive for gitpod. It seems to work well before elasticsearch and kibana are created. The hope is that setting VIZ=false will make gitpod useable with CP Demo.
=> set VIZ=false for gitpod due to resources

docker-compose.yml
- #425 
In a previous commit, I accidentally deleted the connect security extension that enables to /permissions endpoint, so control center could not see the connect cluster.
=> add back connect security extension class so connect is visible from c3

docker-compose.yml, kstreams-app/build.gradle
Forces rebuild and new version of `cp-demo-streams` with a fresh CP 7.3.2 base image.  This will align 11.0 JDK versions and solve a `NoSuchAlgorithmException: Algorithm HmacPBESHA256 not available` problem.
Fixes #438 .
=> cp-demo-kstreams rebuild from fresh base

scripts/helper/create-role-bindings.sh
https://confluentinc.atlassian.net/browse/TMM-84
With Confluent Platform 7.4, `ksqlDBUser` now requires `ResourceOwner` privilege on source topics.  This was `DeveloperRead` previously.
Without this, this error will be seen:
```
Authorization denied to Describe_configs on topic(s): []
```
`ksqlDBUser` now has `ResourceOwner` on two topics.
=> Grant ksqlDBUser ResourceOwner on source topics (CP 7.4 RBAC)

docs/hybrid-cloud.rst
Two fixes for cp-demo docs.
- Adds `ResourceOwner` role-binding required for the cp-demo service account to run Schema Linking.
- Fixes cluster/environment qualification on one role-binding list command.
**Staging Server URL:** http://staging-docs-independent.confluent.io.s3-website-us-west-2.amazonaws.com/docs-platform/PR/2937/7.5/tutorials/cp-demo/docs/hybrid-cloud.html
=> Hybrid cloud docs fixes

docker-compose.yml
Since CP 7.5, we can emit consumer lag via the configuration confluent.consumer.lag.emitter.enabled, see https://docs.confluent.io/platform/current/monitor/monitor-consumer-lag.html#monitor-consumer-lag
To use this functionality in the [jmx-monitoring-stacks](https://github.com/confluentinc/jmx-monitoring-stacks) repository, we first need to enable it in cp-demo.
=> feat(): enable confluent.consumer.lag.emitter

docker-compose.yml
In CP 7.7 the location of secret registry jars has changed, these will already be included in connect's classpath, but need to be added in cub_classpath for the docker image to startup when secret-registry is configured.
=> adding secret registry path in cub_classpath

.gitignore, docker-compose.yml, scripts/start.sh
In KSQL-13533 the (deprecated) monitoring interceptors JAR is missing from ksqlDB Docker image.  This PR patches that for cp-demo by copying the file from Connect worker image.
This change won't apply for CP 8.0 where the monitoring interceptors are deprecated/removed.
=> Fix KSQL-13533 for cp-demo - missing ksqlDB container monitoring-interceptors

.github/ISSUE_TEMPLATE/bug_report.md, docker-compose.yml, scripts/app/throttle_consumer.sh, scripts/ccloud/cluster-link-scratch.sh, scripts/ccloud/create-ccloud-workflow.sh, scripts/ccloud/destroy-ccloud-workflow.sh, scripts/connectors/stop_elasticsearch_sink.sh, scripts/connectors/submit_elastic_sink_config.sh, scripts/connectors/submit_wikipedia_sse_config.sh, scripts/helper/functions.sh, scripts/helper/refresh_mds_login.sh, scripts/ksqlDB/run_ksqlDB.sh, scripts/sbc/add-broker.sh, scripts/sbc/docker-compose.yml, scripts/sbc/validate_sbc_add_broker_completed.sh, scripts/sbc/validate_sbc_add_broker_plan_computation.sh, scripts/sbc/validate_sbc_add_broker_reassignment.sh, scripts/sbc/validate_sbc_kill_broker_completed.sh, scripts/sbc/validate_sbc_kill_broker_started.sh, scripts/start.sh, scripts/stop.sh, scripts/validate/validate_bindings.sh, scripts/validate/validate_ksqldb_processing_log.sh, scripts/validate/validate_rest_proxy.sh
Compose has been a part of Docker for a while now and on Mac I wasn't able to install it standalone next to Docker. Simple aliasing wasn't good enough to pass cp-demo's preflight checks. Best path seemed to be to abandon standalone docker-compose.
=> chore: use Compose built into Docker rather than standalone docker-compose
